name = "embedded-player"
compatibility_date = "2023-06-28"
nodejs_compat = true

[build]
command = "npm install && npm run build"
cwd = "."
[build.upload]
format = "directory"

[site]
bucket = ".next" 