name = "embedded-player-next"
compatibility_date = "2023-06-28"
nodejs_compat = true

[build]
command = "npm run build"
cwd = "."
[build.upload]
format = "directory"

[site]
bucket = ".next/standalone" 